Repository Team-Umbba/Umbba-Server, pull requests merged in 2023-07, with the labels that each got.

#2 [FEAT] 에러 핸들링 + Slack 연동 기능 추가
  build.gradle
  src/main/java/sopt/org/umbbaServer/error/ApiResponse.java
  src/main/java/sopt/org/umbbaServer/error/ControllerExceptionAdvice.java
  src/main/java/sopt/org/umbbaServer/error/CustomException.java
  src/main/java/sopt/org/umbbaServer/error/ErrorType.java
  src/main/java/sopt/org/umbbaServer/error/SuccessType.java
  src/main/java/sopt/org/umbbaServer/util/AuditingTimeEntity.java
  src/main/java/sopt/org/umbbaServer/util/ServerProfileController.java
  src/main/java/sopt/org/umbbaServer/util/slack/SlackApi.java
  src/main/java/sopt/org/umbbaServer/util/slack/SlackTestController.java
Labels: 🔥 Pull Request, 동섭🍑, 🧹Chore, ✨Feat

#4 [FEAT] 소셜 로그인 + JWT 엑세스, 리프레시 토큰 기능 추가
  build.gradle
  src/main/java/sopt/org/umbbaServer/UmbbaServerApplication.java
  src/main/java/sopt/org/umbbaServer/config/SecurityConfig.java
  src/main/java/sopt/org/umbbaServer/domain/user/controller/AuthController.java
  src/main/java/sopt/org/umbbaServer/domain/user/dto/RefreshRequestDto.java
  src/main/java/sopt/org/umbbaServer/domain/user/dto/SocialLoginRequestDto.java
  src/main/java/sopt/org/umbbaServer/domain/user/dto/UserLoginResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/user/jwt/JwtProvider.java
  src/main/java/sopt/org/umbbaServer/domain/user/jwt/JwtValidationType.java
  src/main/java/sopt/org/umbbaServer/domain/user/jwt/TokenDto.java
  src/main/java/sopt/org/umbbaServer/domain/user/jwt/redis/RefreshToken.java
  src/main/java/sopt/org/umbbaServer/domain/user/jwt/redis/TokenRepository.java
  src/main/java/sopt/org/umbbaServer/domain/user/jwt/security/CustomJwtAuthenticationEntryPoint.java
  src/main/java/sopt/org/umbbaServer/domain/user/jwt/security/JwtAuthenticationFilter.java
  src/main/java/sopt/org/umbbaServer/domain/user/jwt/security/UserAuthentication.java
  src/main/java/sopt/org/umbbaServer/domain/user/model/User.java
  src/main/java/sopt/org/umbbaServer/domain/user/repository/UserRepository.java
  src/main/java/sopt/org/umbbaServer/domain/user/service/AuthService.java
  src/main/java/sopt/org/umbbaServer/domain/user/social/SocialPlatform.java
  src/main/java/sopt/org/umbbaServer/domain/user/social/apple/AppleLoginService.java
  src/main/java/sopt/org/umbbaServer/domain/user/social/apple/feign/AppleApiClient.java
  src/main/java/sopt/org/umbbaServer/domain/user/social/apple/response/ApplePublicKey.java
  src/main/java/sopt/org/umbbaServer/domain/user/social/apple/response/ApplePublicKeys.java
  src/main/java/sopt/org/umbbaServer/domain/user/social/apple/verify/AppleClaimsValidator.java
  src/main/java/sopt/org/umbbaServer/domain/user/social/apple/verify/AppleJwtParser.java
  src/main/java/sopt/org/umbbaServer/domain/user/social/apple/verify/EncryptUtils.java
  src/main/java/sopt/org/umbbaServer/domain/user/social/apple/verify/PublicKeyGenerator.java
  src/main/java/sopt/org/umbbaServer/domain/user/social/kakao/KakaoLoginService.java
  src/main/java/sopt/org/umbbaServer/domain/user/social/kakao/feign/KakaoApiClient.java
  src/main/java/sopt/org/umbbaServer/domain/user/social/kakao/feign/KakaoAuthApiClient.java
  src/main/java/sopt/org/umbbaServer/domain/user/social/kakao/response/KakaoAccessTokenResponse.java
  src/main/java/sopt/org/umbbaServer/domain/user/social/kakao/response/KakaoAccount.java
  src/main/java/sopt/org/umbbaServer/domain/user/social/kakao/response/KakaoUserProfile.java
  src/main/java/sopt/org/umbbaServer/domain/user/social/kakao/response/KakaoUserResponse.java
  src/main/java/sopt/org/umbbaServer/error/ErrorType.java
  src/main/java/sopt/org/umbbaServer/error/SuccessType.java
  src/main/resources/application.yaml
Labels: 🔥 Pull Request, 동섭🍑, ✨Feat, 🪄API, 🔨Refactor

#6 [FIX] deploy.sh 실행에서 사용하는 API들 SecurityConfig에서 풀어주기
  src/main/java/sopt/org/umbbaServer/config/SecurityConfig.java
Labels: 🔥 Pull Request, 동섭🍑, 🐞 BugFix, 🚀Deploy

#11 [FEAT] ERD를 바탕으로 엔티티 생성
  src/main/java/sopt/org/umbbaServer/domain/parentchild/model/ParentChild.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/model/ParentChildRelation.java
  src/main/java/sopt/org/umbbaServer/domain/qna/example
  src/main/java/sopt/org/umbbaServer/domain/qna/model/QnA.java
  src/main/java/sopt/org/umbbaServer/domain/qna/model/Question.java
  src/main/java/sopt/org/umbbaServer/domain/qna/model/QuestionEffect.java
  src/main/java/sopt/org/umbbaServer/domain/qna/model/QuestionSection.java
  src/main/java/sopt/org/umbbaServer/domain/user/model/User.java
Labels: 🔥 Pull Request, 동섭🍑, ✨Feat, ☁️Database

#15 [FEAT] 온보딩 부모자식 관계 정보 입력(초대하는 측) API
  build.gradle
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/ParentchildController.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/request/OnboardingInviteRequestDto.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/request/OnboardingReceiveRequestDto.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/response/OnboadringReceiveResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/response/OnboardingInviteResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/model/Parentchild.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/respository/ParentchildRepository.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/service/ParentchildService.java
  src/main/java/sopt/org/umbbaServer/domain/qna/model/QnA.java
  src/main/java/sopt/org/umbbaServer/domain/user/controller/dto/request/UserInfoDto.java
  src/main/java/sopt/org/umbbaServer/domain/user/controller/dto/response/UserLoginResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/user/model/User.java
  src/main/java/sopt/org/umbbaServer/global/common/dto/ApiResponse.java
  src/main/java/sopt/org/umbbaServer/global/config/jwt/JwtProvider.java
  src/main/java/sopt/org/umbbaServer/global/exception/ErrorType.java
  src/main/java/sopt/org/umbbaServer/global/exception/SuccessType.java
Labels: 🔥 Pull Request, 예준🍒, ✨Feat, 🪄API, ☁️Database

#17 [FEAT] 일일문답 페이지 최근 질문과 답변 조회 API 구현
  README.md
  src/main/java/sopt/org/umbbaServer/UmbbaServerApplication.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/repository/ParentchildRepository.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/respository/ParentchildRepository.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/service/ParentchildService.java
  src/main/java/sopt/org/umbbaServer/domain/qna/controller/QnAController.java
  src/main/java/sopt/org/umbbaServer/domain/qna/controller/dto/response/TodayQnAResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/qna/model/QnA.java
  src/main/java/sopt/org/umbbaServer/domain/qna/model/QuestionEffect.java
  src/main/java/sopt/org/umbbaServer/domain/qna/model/QuestionSection.java
  src/main/java/sopt/org/umbbaServer/domain/qna/repository/QnARepository.java
  src/main/java/sopt/org/umbbaServer/domain/qna/repository/QuestionRepository.java
  src/main/java/sopt/org/umbbaServer/domain/qna/service/QnAService.java
  src/main/java/sopt/org/umbbaServer/global/config/SecurityConfig.java
  src/main/java/sopt/org/umbbaServer/global/exception/ErrorType.java
  src/main/java/sopt/org/umbbaServer/global/exception/SuccessType.java
Labels: 🔥 Pull Request, 동섭🍑, ✨Feat, 🪄API

#20 [FEAT] 초대코드 입력 및 온보딩 정보 입력(초대받는 측) API
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/ParentchildController.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/request/InviteCodeRequestDto.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/request/OnboardingInviteRequestDto.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/request/OnboardingReceiveRequestDto.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/response/GetInviteCodeResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/response/InviteResultResponeDto.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/response/OnboadringReceiveResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/response/OnboardingReceiveResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/model/Parentchild.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/repository/ParentchildRepository.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/service/ParentchildService.java
  src/main/java/sopt/org/umbbaServer/domain/qna/model/QnA.java
  src/main/java/sopt/org/umbbaServer/domain/qna/service/QnAService.java
  src/main/java/sopt/org/umbbaServer/domain/user/model/User.java
  src/main/java/sopt/org/umbbaServer/domain/user/repository/UserRepository.java
  src/main/java/sopt/org/umbbaServer/global/common/dto/ApiResponse.java
  src/main/java/sopt/org/umbbaServer/global/config/SecurityConfig.java
  src/main/java/sopt/org/umbbaServer/global/config/jwt/JwtProvider.java
  src/main/java/sopt/org/umbbaServer/global/exception/ErrorType.java
  src/main/java/sopt/org/umbbaServer/global/exception/SuccessType.java
Labels: 🔥 Pull Request, 예준🍒, ✨Feat, 🪄API, 🧵Git

#21 [FEAT] 일일문답 페이지 질문 답변 API
  src/main/java/sopt/org/umbbaServer/domain/qna/controller/QnAController.java
  src/main/java/sopt/org/umbbaServer/domain/qna/controller/dto/request/TodayAnswerRequestDto.java
  src/main/java/sopt/org/umbbaServer/domain/qna/model/QnA.java
  src/main/java/sopt/org/umbbaServer/domain/qna/service/QnAService.java
  src/main/java/sopt/org/umbbaServer/global/exception/SuccessType.java
Labels: 🔥 Pull Request, 동섭🍑, ✨Feat, 🪄API

#24 [FEAT] 홈 화면 관련 API
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/ParentchildController.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/response/GetInviteCodeResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/dao/ParentchildDao.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/service/ParentchildService.java
  src/main/java/sopt/org/umbbaServer/domain/qna/controller/QnAController.java
  src/main/java/sopt/org/umbbaServer/domain/qna/controller/dto/response/GetMainViewResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/qna/dao/QnADao.java
  src/main/java/sopt/org/umbbaServer/domain/qna/repository/QnARepository.java
  src/main/java/sopt/org/umbbaServer/domain/qna/service/QnAService.java
  src/main/java/sopt/org/umbbaServer/global/exception/SuccessType.java
  src/main/resources/application.yaml
Labels: 🔥 Pull Request, 예준🍒, ✨Feat, 🪄API

#27 [REFACTOR] 일일문답과 리스트 관련 API 리팩토링
  src/main/java/sopt/org/umbbaServer/domain/qna/controller/QnAController.java
  src/main/java/sopt/org/umbbaServer/domain/qna/controller/dto/response/QnAListResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/qna/controller/dto/response/SingleQnAResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/qna/controller/dto/response/TodayQnAResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/qna/service/QnAService.java
  src/main/java/sopt/org/umbbaServer/global/exception/ErrorType.java
Labels: 🔥 Pull Request, 동섭🍑, 🪄API, 🔨Refactor

#29 [REFACTOR] 온보딩, 홈 화면 API 리팩토링
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/ParentchildController.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/request/InviteCodeRequestDto.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/request/OnboardingInviteRequestDto.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/request/OnboardingReceiveRequestDto.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/response/GetInviteCodeResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/response/InviteResultResponeDto.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/response/OnboardingInviteResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/response/OnboardingReceiveResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/service/ParentchildService.java
  src/main/java/sopt/org/umbbaServer/domain/qna/controller/dto/response/GetMainViewResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/user/controller/dto/request/UserInfoDto.java
  src/main/java/sopt/org/umbbaServer/domain/user/model/User.java
  src/main/java/sopt/org/umbbaServer/domain/user/service/AuthService.java
Labels: 🔥 Pull Request, 예준🍒, 🧹Chore, 🪄API, 🔨Refactor

#31 [REFACTOR] 유저 인증 관련 API 리팩토링
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/request/OnboardingInviteRequestDto.java
  src/main/java/sopt/org/umbbaServer/domain/qna/controller/QnAController.java
  src/main/java/sopt/org/umbbaServer/domain/qna/controller/dto/request/TodayAnswerRequestDto.java
  src/main/java/sopt/org/umbbaServer/domain/qna/controller/dto/response/GetMainViewResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/qna/controller/dto/response/QnAListResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/qna/controller/dto/response/SingleQnAResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/qna/controller/dto/response/TodayQnAResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/qna/service/QnAService.java
  src/main/java/sopt/org/umbbaServer/domain/user/controller/AuthController.java
  src/main/java/sopt/org/umbbaServer/domain/user/controller/dto/response/UserLoginResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/user/model/User.java
  src/main/java/sopt/org/umbbaServer/domain/user/service/AuthService.java
  src/main/java/sopt/org/umbbaServer/global/common/advice/ControllerExceptionAdvice.java
  src/main/java/sopt/org/umbbaServer/global/config/jwt/TokenDto.java
  src/main/java/sopt/org/umbbaServer/global/exception/ErrorType.java
  src/main/java/sopt/org/umbbaServer/global/exception/SuccessType.java
Labels: 🔥 Pull Request, 동섭🍑, ✨Feat, 🪄API, 🔨Refactor

#32 [FIX] 요청, 응답 값에 관한 에러 해결
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/ParentchildController.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/request/InviteCodeRequestDto.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/request/OnboardingInviteRequestDto.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/request/OnboardingReceiveRequestDto.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/response/InviteResultResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/response/OnboardingInviteResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/response/OnboardingReceiveResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/dao/ParentchildDao.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/service/ParentchildService.java
  src/main/java/sopt/org/umbbaServer/domain/qna/controller/dto/response/GetMainViewResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/qna/service/QnAService.java
  src/main/java/sopt/org/umbbaServer/domain/user/controller/dto/request/UserInfoDto.java
  src/main/java/sopt/org/umbbaServer/global/common/advice/ControllerExceptionAdvice.java
  src/main/java/sopt/org/umbbaServer/global/common/dto/ApiResponse.java
  src/main/java/sopt/org/umbbaServer/global/exception/ErrorType.java
Labels: 🔥 Pull Request, 예준🍒, 🐞 BugFix, 🧹Chore, ✨Feat, 🔨Refactor

#35 [FIX] 회원탈퇴시에 소셜 플랫폼 필드가 변경되도록 변경
  src/main/java/sopt/org/umbbaServer/domain/user/controller/AuthController.java
  src/main/java/sopt/org/umbbaServer/domain/user/model/User.java
  src/main/java/sopt/org/umbbaServer/domain/user/social/SocialPlatform.java
Labels: 🔥 Pull Request, 🚨Hotfix, 동섭🍑, 🪄API

#37 [FEAT] 메인 홈 API 통합 및 추가기능 반영
  src/main/java/sopt/org/umbbaServer/UmbbaServerApplication.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/ParentchildController.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/response/GetInviteCodeResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/dao/ParentchildDao.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/repository/ParentchildRepository.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/service/ParentchildService.java
  src/main/java/sopt/org/umbbaServer/domain/qna/controller/dto/response/GetMainViewResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/qna/controller/dto/response/TodayQnAResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/qna/dao/QnADao.java
  src/main/java/sopt/org/umbbaServer/domain/qna/repository/QnARepository.java
  src/main/java/sopt/org/umbbaServer/domain/qna/service/QnAService.java
  src/main/java/sopt/org/umbbaServer/domain/user/controller/AuthController.java
  src/main/java/sopt/org/umbbaServer/domain/user/controller/dto/request/UserInfoDto.java
  src/main/java/sopt/org/umbbaServer/domain/user/model/User.java
  src/main/java/sopt/org/umbbaServer/domain/user/repository/UserRepository.java
  src/main/java/sopt/org/umbbaServer/domain/user/service/AuthService.java
  src/main/java/sopt/org/umbbaServer/global/common/advice/ControllerExceptionAdvice.java
  src/main/java/sopt/org/umbbaServer/global/config/SecurityConfig.java
  src/main/java/sopt/org/umbbaServer/global/config/jwt/JwtProvider.java
  src/main/java/sopt/org/umbbaServer/global/exception/ErrorType.java
Labels: 🔥 Pull Request, 예준🍒, ✨Feat, 🪄API, 🔧Modify

#39 [FEAT] 온보딩에서 진행한 선택질문에 따라 사용자에게 맞춘 질문 리스트 생성 기능 구현
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/ParentchildController.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/request/OnboardingInviteRequestDto.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/request/OnboardingReceiveRequestDto.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/model/Parentchild.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/service/ParentchildService.java
  src/main/java/sopt/org/umbbaServer/domain/qna/controller/QnAController.java
  src/main/java/sopt/org/umbbaServer/domain/qna/model/OnboardingAnswer.java
  src/main/java/sopt/org/umbbaServer/domain/qna/model/Question.java
  src/main/java/sopt/org/umbbaServer/domain/qna/model/QuestionGroup.java
  src/main/java/sopt/org/umbbaServer/domain/qna/model/QuestionSection.java
  src/main/java/sopt/org/umbbaServer/domain/qna/repository/QuestionRepository.java
  src/main/java/sopt/org/umbbaServer/domain/qna/service/QnAService.java
Labels: 동섭🍑, ✨Feat, 🪄API, ☁️Database

#41 [FEAT] FCM 푸시 서버 구축
  .gitignore
  build.gradle
  src/main/java/sopt/org/umbbaServer/domain/user/model/User.java
  src/main/java/sopt/org/umbbaServer/domain/user/repository/UserRepository.java
  src/main/java/sopt/org/umbbaServer/global/config/FCMConfig.java
  src/main/java/sopt/org/umbbaServer/global/config/ScheduleConfig.java
  src/main/java/sopt/org/umbbaServer/global/exception/ErrorType.java
  src/main/java/sopt/org/umbbaServer/global/exception/SuccessType.java
  src/main/java/sopt/org/umbbaServer/global/util/fcm/FCMScheduler.java
  src/main/java/sopt/org/umbbaServer/global/util/fcm/FCMService.java
  src/main/java/sopt/org/umbbaServer/global/util/fcm/PushRequest.java
  src/main/java/sopt/org/umbbaServer/global/util/fcm/controller/FCMController.java
  src/main/java/sopt/org/umbbaServer/global/util/fcm/controller/dto/FCMMessage.java
  src/main/java/sopt/org/umbbaServer/global/util/fcm/controller/dto/FCMNotificationRequestDto.java
  src/main/resources/application.yaml
Labels: 🔥 Pull Request, 예준🍒, ✨Feat, 🪄API, ☁️Database

#44 [FIX] 온보딩 dto 관련 버그 수정
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/request/OnboardingInviteRequestDto.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/request/OnboardingReceiveRequestDto.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/response/OnboardingInviteResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/response/OnboardingReceiveResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/dao/ParentchildDao.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/model/Parentchild.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/service/ParentchildService.java
  src/main/java/sopt/org/umbbaServer/domain/qna/controller/dto/request/TodayAnswerRequestDto.java
  src/main/java/sopt/org/umbbaServer/domain/qna/controller/dto/response/QnAListResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/qna/model/OnboardingAnswer.java
  src/main/java/sopt/org/umbbaServer/domain/qna/service/QnAService.java
  src/main/java/sopt/org/umbbaServer/domain/user/controller/dto/request/RefreshRequestDto.java
  src/main/java/sopt/org/umbbaServer/domain/user/controller/dto/request/SocialLoginRequestDto.java
  src/main/java/sopt/org/umbbaServer/domain/user/service/AuthService.java
  src/main/java/sopt/org/umbbaServer/global/exception/ErrorType.java
Labels: 🔥 Pull Request, 🚨Hotfix, 동섭🍑, 🪄API, ☁️Database

#46 [FEAT] 초대장 조회 API로 로직 분리
  src/main/java/sopt/org/umbbaServer/domain/qna/controller/QnAController.java
  src/main/java/sopt/org/umbbaServer/domain/qna/controller/dto/response/GetInvitationResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/qna/controller/dto/response/TodayQnAResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/qna/service/QnAService.java
Labels: 🔥 Pull Request, 예준🍒, ✨Feat, 🪄API, 🔧Modify

#47 [FEAT] 주기적인 알림 메세지 전송 및 리팩토링
  src/main/java/sopt/org/umbbaServer/domain/parentchild/dao/ParentchildDao.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/repository/ParentchildRepository.java
  src/main/java/sopt/org/umbbaServer/domain/qna/dao/QnADao.java
  src/main/java/sopt/org/umbbaServer/domain/qna/model/Question.java
  src/main/java/sopt/org/umbbaServer/domain/qna/model/QuestionGroup.java
  src/main/java/sopt/org/umbbaServer/domain/qna/model/QuestionType.java
  src/main/java/sopt/org/umbbaServer/domain/qna/repository/QuestionRepository.java
  src/main/java/sopt/org/umbbaServer/domain/qna/service/QnAService.java
  src/main/java/sopt/org/umbbaServer/domain/user/controller/dto/request/SocialLoginRequestDto.java
  src/main/java/sopt/org/umbbaServer/domain/user/controller/dto/response/UserLoginResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/user/model/User.java
  src/main/java/sopt/org/umbbaServer/domain/user/repository/UserRepository.java
  src/main/java/sopt/org/umbbaServer/domain/user/service/AuthService.java
  src/main/java/sopt/org/umbbaServer/global/config/FCMConfig.java
  src/main/java/sopt/org/umbbaServer/global/config/ScheduleConfig.java
  src/main/java/sopt/org/umbbaServer/global/config/SecurityConfig.java
  src/main/java/sopt/org/umbbaServer/global/exception/SuccessType.java
  src/main/java/sopt/org/umbbaServer/global/util/fcm/FCMScheduler.java
  src/main/java/sopt/org/umbbaServer/global/util/fcm/FCMService.java
  src/main/java/sopt/org/umbbaServer/global/util/fcm/PushRequest.java
  src/main/java/sopt/org/umbbaServer/global/util/fcm/controller/FCMController.java
  src/main/java/sopt/org/umbbaServer/global/util/fcm/controller/dto/FCMMessage.java
  src/main/java/sopt/org/umbbaServer/global/util/fcm/controller/dto/FCMNotificationRequestDto.java
  src/main/java/sopt/org/umbbaServer/global/util/fcm/controller/dto/FCMPushRequestDto.java
  src/main/java/sopt/org/umbbaServer/global/util/fcm/controller/dto/PushMessage.java
  src/main/resources/application.yaml
Labels: 🔥 Pull Request, 예준🍒, 🧹Chore, ✨Feat, 🪄API, 🔨Refactor

#48 [FIX] section의 value를 결혼시절에서 우리가만나고로 변경
  src/main/java/sopt/org/umbbaServer/domain/qna/model/QuestionSection.java
Labels: 🔥 Pull Request, 🚨Hotfix, 동섭🍑, 🧹Chore, 🪄API

#53 [FEAT] 지금 몇일차 질문에 대해 문답을 나누고 있는지 저장하는 필드 추가
  src/main/java/sopt/org/umbbaServer/domain/parentchild/model/Parentchild.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/service/ParentchildService.java
  src/main/java/sopt/org/umbbaServer/domain/qna/controller/dto/response/TodayQnAResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/qna/service/QnAService.java
Labels: 동섭🍑, ✨Feat, 🪄API, ☁️Database

#54 [FEAT] 과거의 문답 개별 조회 API에서도 index 추가
  src/main/java/sopt/org/umbbaServer/domain/qna/controller/dto/response/SingleQnAResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/qna/service/QnAService.java
Labels: 🔥 Pull Request, 동섭🍑, ✨Feat, 🪄API

#56 [FIX] 클라이언트 API 붙이는 작업 중 발생한 오류 수정
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/ParentchildController.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/service/ParentchildService.java
  src/main/java/sopt/org/umbbaServer/domain/qna/dao/QnADao.java
  src/main/java/sopt/org/umbbaServer/domain/qna/repository/QuestionRepository.java
  src/main/java/sopt/org/umbbaServer/domain/qna/service/QnAService.java
  src/main/java/sopt/org/umbbaServer/domain/user/controller/dto/request/SocialLoginRequestDto.java
  src/main/java/sopt/org/umbbaServer/domain/user/controller/dto/request/UserInfoDto.java
  src/main/java/sopt/org/umbbaServer/domain/user/controller/dto/response/UserLoginResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/user/model/User.java
  src/main/java/sopt/org/umbbaServer/domain/user/service/AuthService.java
  src/main/java/sopt/org/umbbaServer/domain/user/social/SocialPlatform.java
  src/main/java/sopt/org/umbbaServer/global/config/ScheduleConfig.java
Labels: 🔥 Pull Request, 🚨Hotfix, 동섭🍑, 🪄API

#57 [FIX] 클라이언트 API 붙이는 작업 중 발생한 오류 수정
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/request/InviteCodeRequestDto.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/service/ParentchildService.java
  src/main/java/sopt/org/umbbaServer/domain/user/controller/dto/response/UserLoginResponseDto.java
  src/main/java/sopt/org/umbbaServer/domain/user/model/User.java
  src/main/java/sopt/org/umbbaServer/domain/user/service/AuthService.java
  src/main/java/sopt/org/umbbaServer/domain/user/social/apple/verify/AppleClaimsValidator.java
  src/main/resources/application.yaml
Labels: 🔥 Pull Request, 동섭🍑, 🐞 BugFix, ✨Feat, 🪄API, ☁️Database

#58 [REFACTOR] Parentchild 엔티티에 관한 비즈니스 로직 리팩토링 및 푸시알림 필터링 로직 추가
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/ParentchildController.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/model/Parentchild.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/model/ParentchildRelation.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/service/ParentchildService.java
  src/main/java/sopt/org/umbbaServer/domain/qna/dao/QnADao.java
  src/main/java/sopt/org/umbbaServer/domain/qna/service/QnAService.java
  src/main/java/sopt/org/umbbaServer/domain/user/model/User.java
  src/main/java/sopt/org/umbbaServer/domain/user/service/AuthService.java
  src/main/java/sopt/org/umbbaServer/global/config/SecurityConfig.java
  src/main/java/sopt/org/umbbaServer/global/exception/ErrorType.java
  src/main/java/sopt/org/umbbaServer/global/util/fcm/FCMScheduler.java
  src/main/java/sopt/org/umbbaServer/global/util/fcm/FCMService.java
  src/main/java/sopt/org/umbbaServer/global/util/fcm/controller/FCMController.java
  src/main/java/sopt/org/umbbaServer/global/util/fcm/controller/dto/FCMPushRequestDto.java
  src/main/java/sopt/org/umbbaServer/global/util/fcm/controller/dto/PushMessage.java
Labels: 🔥 Pull Request, 예준🍒, 🐞 BugFix, ✨Feat, 🪄API, 🔨Refactor

#60 [FIX] hasAlarm 필드 다시 삭제 (서버에서 보관 필요 없으므로)
  src/main/java/sopt/org/umbbaServer/domain/user/model/User.java
  src/main/java/sopt/org/umbbaServer/domain/user/service/AuthService.java
Labels: 🔥 Pull Request, 🚨Hotfix, 동섭🍑, ☁️Database

#62 [FIX] 매일 같은 시간에 전송되는 푸시 알림이 2번씩 전송되는 오류 해결
  src/main/java/sopt/org/umbbaServer/global/util/fcm/FCMScheduler.java
  src/main/java/sopt/org/umbbaServer/global/util/fcm/FCMService.java
  src/main/java/sopt/org/umbbaServer/global/util/fcm/controller/FCMController.java
Labels: 🔥 Pull Request, 🚨Hotfix, 동섭🍑, 🔧Modify

#65 [MODIFY] 사용자 맞춤형 질문 제공을 위한 로직 추가
  src/main/java/sopt/org/umbbaServer/domain/parentchild/service/ParentchildService.java
  src/main/java/sopt/org/umbbaServer/domain/qna/dao/QnADao.java
  src/main/java/sopt/org/umbbaServer/domain/qna/model/QnA.java
  src/main/java/sopt/org/umbbaServer/domain/qna/model/QuestionSection.java
  src/main/java/sopt/org/umbbaServer/domain/qna/model/QuestionType.java
  src/main/java/sopt/org/umbbaServer/domain/qna/repository/QuestionRepository.java
  src/main/java/sopt/org/umbbaServer/domain/qna/service/QnAService.java
  src/main/java/sopt/org/umbbaServer/global/util/fcm/FCMService.java
  src/main/resources/application.yaml
Labels: 🔥 Pull Request, 동섭🍑, 🪄API, 🔧Modify

#66 [FEAT] 푸시알림 스케줄링 예약 작업 초기화
  src/main/java/sopt/org/umbbaServer/UmbbaServerApplication.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/model/Parentchild.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/service/ParentchildService.java
  src/main/java/sopt/org/umbbaServer/domain/qna/model/QuestionType.java
  src/main/java/sopt/org/umbbaServer/global/config/ScheduleConfig.java
  src/main/java/sopt/org/umbbaServer/global/util/fcm/FCMScheduler.java
  src/main/java/sopt/org/umbbaServer/global/util/fcm/FCMService.java
  src/main/resources/application.yaml
Labels: 🔥 Pull Request, 🚨Hotfix, 예준🍒, 🐞 BugFix, ✨Feat, 🔧Modify

#69 [FIX] 초대 받는측이 온보딩을 안끝냈을 때 질문 답변할 수 없도록 변경
  src/main/java/sopt/org/umbbaServer/domain/qna/service/QnAService.java
Labels: 🔥 Pull Request, 🚨Hotfix, 동섭🍑, 🪄API, 🔧Modify

#74 [FIX] 선택 질문에 대한 유저의 답변이 일정 수 이상 되어야 custom이 이루어지게 수정
  src/main/java/sopt/org/umbbaServer/domain/qna/service/QnAService.java
Labels: 🔥 Pull Request, 🚨Hotfix, 동섭🍑, 🪄API

#75 [REFACTOR] 꼼꼼한 예외처리 추가
  README.md
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/ParentchildController.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/controller/dto/request/OnboardingInviteRequestDto.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/model/ParentchildRelation.java
  src/main/java/sopt/org/umbbaServer/domain/parentchild/service/ParentchildService.java
  src/main/java/sopt/org/umbbaServer/domain/qna/service/QnAService.java
  src/main/java/sopt/org/umbbaServer/global/common/advice/ControllerExceptionAdvice.java
  src/main/java/sopt/org/umbbaServer/global/common/dto/ApiResponse.java
  src/main/java/sopt/org/umbbaServer/global/exception/ErrorType.java
  src/main/java/sopt/org/umbbaServer/global/exception/SuccessType.java
  src/main/java/sopt/org/umbbaServer/global/util/fcm/FCMService.java
Labels: 🔥 Pull Request, 예준🍒, 🧹Chore, 🔨Refactor

#78 [FIX] 급한 에러사항 수정
  src/main/java/sopt/org/umbbaServer/domain/parentchild/service/ParentchildService.java
Labels: 🔥 Pull Request, 🚨Hotfix, 예준🍒

#79 [FIX] 일일문답과 리스트 관련 에러 처리 중 수정사항 반영
  src/main/java/sopt/org/umbbaServer/domain/qna/model/QuestionSection.java
  src/main/java/sopt/org/umbbaServer/domain/qna/service/QnAService.java
  src/main/java/sopt/org/umbbaServer/global/exception/ErrorType.java
Labels: 🔥 Pull Request, 동섭🍑, 🐞 BugFix, 🪄API

#80 [FEAT] 데모데이 시연을 위한 테스트용 API
  src/main/java/sopt/org/umbbaServer/domain/qna/controller/QnAController.java
  src/main/java/sopt/org/umbbaServer/domain/qna/controller/dto/request/TodayAnswerRequestDto.java
  src/main/java/sopt/org/umbbaServer/domain/qna/service/QnAService.java
  src/main/java/sopt/org/umbbaServer/global/common/DemoController.java
  src/main/java/sopt/org/umbbaServer/global/config/SecurityConfig.java
  src/main/java/sopt/org/umbbaServer/global/exception/SuccessType.java
  src/main/java/sopt/org/umbbaServer/global/util/fcm/FCMScheduler.java
  src/main/java/sopt/org/umbbaServer/global/util/fcm/FCMService.java
Labels: 🔥 Pull Request, 🚨Hotfix, 예준🍒, ✨Feat, 🪄API, 🔧Modify

#81 [FIX] 테스트용 알람 주석 처리
  src/main/java/sopt/org/umbbaServer/global/util/fcm/FCMScheduler.java
  src/main/java/sopt/org/umbbaServer/global/util/fcm/controller/FCMController.java
Labels: 🔥 Pull Request, 🚨Hotfix, 동섭🍑
