Repository Team-Umbba/Umbba-Server, pull requests merged in 2023-08, with the labels that each got.

#83 [REFACTOR] common과 external 모듈 분리
  src/main/java/sopt/org/umbba/domain/user/social/SocialPlatform.java
  src/main/java/sopt/org/umbba/domain/user/social/apple/AppleLoginService.java
  src/main/java/sopt/org/umbba/domain/user/social/apple/verify/AppleClaimsValidator.java
  src/main/java/sopt/org/umbba/domain/user/social/apple/verify/AppleJwtParser.java
  src/main/java/sopt/org/umbba/domain/user/social/apple/verify/EncryptUtils.java
  src/main/java/sopt/org/umbba/domain/user/social/apple/verify/PublicKeyGenerator.java
  src/main/java/sopt/org/umbba/domain/user/social/kakao/KakaoLoginService.java
  umbba-common/build.gradle
  umbba-common/src/main/java/sopt/org/umbba/common/exception/ErrorType.java
  umbba-common/src/main/java/sopt/org/umbba/common/exception/SuccessType.java
  umbba-common/src/main/java/sopt/org/umbba/common/exception/dto/ApiResponse.java
  umbba-common/src/main/java/sopt/org/umbba/common/exception/model/CustomException.java
  umbba-common/src/main/java/sopt/org/umbba/common/sqs/MessageType.java
  umbba-common/src/main/java/sopt/org/umbba/common/sqs/MessageUtils.java
  umbba-common/src/main/java/sopt/org/umbba/common/sqs/dto/FirebaseDto.java
  umbba-common/src/main/java/sopt/org/umbba/common/sqs/dto/MessageDto.java
  umbba-common/src/main/java/sopt/org/umbba/common/sqs/dto/SlackDto.java
  umbba-external/src/main/java/sopt/org/umbba/external/client/auth/apple/AppleApiClient.java
  umbba-external/src/main/java/sopt/org/umbba/external/client/auth/apple/response/ApplePublicKey.java
  umbba-external/src/main/java/sopt/org/umbba/external/client/auth/apple/response/ApplePublicKeys.java
  umbba-external/src/main/java/sopt/org/umbba/external/client/auth/kakao/KakaoApiClient.java
  umbba-external/src/main/java/sopt/org/umbba/external/client/auth/kakao/KakaoAuthApiClient.java
  umbba-external/src/main/java/sopt/org/umbba/external/client/auth/kakao/response/KakaoAccessTokenResponse.java
  umbba-external/src/main/java/sopt/org/umbba/external/client/auth/kakao/response/KakaoAccount.java
  umbba-external/src/main/java/sopt/org/umbba/external/client/auth/kakao/response/KakaoUserProfile.java
  umbba-external/src/main/java/sopt/org/umbba/external/client/auth/kakao/response/KakaoUserResponse.java
Labels: 동섭🍑, 🔨Refactor

#84 [Refactor] umbba-domain 모듈 분리
  umbba-domain/build.gradle
  umbba-domain/src/main/java/sopt/org/umbba/domain/config/jpa/JpaConfig.java
  umbba-domain/src/main/java/sopt/org/umbba/domain/domain/common/AuditingTimeEntity.java
  umbba-domain/src/main/java/sopt/org/umbba/domain/domain/parentchild/Parentchild.java
  umbba-domain/src/main/java/sopt/org/umbba/domain/domain/parentchild/ParentchildRelation.java
  umbba-domain/src/main/java/sopt/org/umbba/domain/domain/parentchild/repository/ParentchildRepository.java
  umbba-domain/src/main/java/sopt/org/umbba/domain/domain/qna/OnboardingAnswer.java
  umbba-domain/src/main/java/sopt/org/umbba/domain/domain/qna/QnA.java
  umbba-domain/src/main/java/sopt/org/umbba/domain/domain/qna/Question.java
  umbba-domain/src/main/java/sopt/org/umbba/domain/domain/qna/QuestionSection.java
  umbba-domain/src/main/java/sopt/org/umbba/domain/domain/qna/QuestionType.java
  umbba-domain/src/main/java/sopt/org/umbba/domain/domain/qna/repository/QnARepository.java
  umbba-domain/src/main/java/sopt/org/umbba/domain/domain/qna/repository/QuestionRepository.java
  umbba-domain/src/main/java/sopt/org/umbba/domain/domain/user/SocialPlatform.java
  umbba-domain/src/main/java/sopt/org/umbba/domain/domain/user/User.java
  umbba-domain/src/main/java/sopt/org/umbba/domain/domain/user/repository/UserRepository.java
Labels: 🔥 Pull Request, 예준🍒, 🔨Refactor

#85 [REFACTOR] Notification 서버 로직 분리
  umbba-domain/src/main/java/sopt/org/umbba/domain/domain/qna/OnboardingAnswer.java
  umbba-notification/.gitignore
  umbba-notification/src/main/java/sopt/org/umbba/notification/config/fcm/FCMConfig.java
  umbba-notification/src/main/java/sopt/org/umbba/notification/config/scheduler/ScheduleConfig.java
  umbba-notification/src/main/java/sopt/org/umbba/notification/config/sqs/SqsConfig.java
  umbba-notification/src/main/java/sopt/org/umbba/notification/controller/fcm/FCMController.java
  umbba-notification/src/main/java/sopt/org/umbba/notification/controller/fcm/dto/FCMMessage.java
  umbba-notification/src/main/java/sopt/org/umbba/notification/controller/fcm/dto/FCMPushRequestDto.java
  umbba-notification/src/main/java/sopt/org/umbba/notification/controller/fcm/dto/PushMessage.java
  umbba-notification/src/main/java/sopt/org/umbba/notification/controller/slack/SlackTestController.java
  umbba-notification/src/main/java/sopt/org/umbba/notification/service/fcm/FCMService.java
  umbba-notification/src/main/java/sopt/org/umbba/notification/service/scheduler/FCMScheduler.java
  umbba-notification/src/main/java/sopt/org/umbba/notification/service/slack/SlackApi.java
  umbba-notification/src/main/resources/application.yaml
Labels: 🔥 Pull Request, 예준🍒, 🧹Chore, 🔨Refactor

#89 [FIX] EntityManager close 추가
  build.gradle
  src/main/java/sopt/org/umbbaServer/global/util/fcm/FCMService.java
  src/main/resources/application.yaml
Labels: 🔥 Pull Request, 🚨Hotfix, 예준🍒, 🐞 BugFix

#90 [FIX] 추가 변경 사항 반영
  src/main/java/sopt/org/umbbaServer/domain/user/service/AuthService.java
  src/main/java/sopt/org/umbbaServer/global/common/advice/ControllerExceptionAdvice.java
  src/main/java/sopt/org/umbbaServer/global/util/fcm/FCMService.java
  src/main/resources/application.yaml
Labels: 🔥 Pull Request, 예준🍒, 🐞 BugFix, 🧹Chore

#91 [FEAT] AWS SQS를 이용한 푸시알림 구현
  umbba-api/build.gradle
  umbba-api/src/main/java/sopt/org/umbba/api/config/sqs/SqsConfig.java
  umbba-api/src/main/java/sopt/org/umbba/api/config/sqs/producer/SqsProducer.java
  umbba-api/src/main/java/sopt/org/umbba/api/controller/advice/ControllerExceptionAdvice.java
  umbba-api/src/main/java/sopt/org/umbba/api/controller/health/DemoController.java
  umbba-api/src/main/java/sopt/org/umbba/api/service/notification/NotificationService.java
  umbba-api/src/main/java/sopt/org/umbba/api/service/qna/QnAService.java
  umbba-api/src/main/java/sopt/org/umbba/api/service/user/AuthService.java
  umbba-api/src/main/resources/application.yaml
  umbba-common/src/main/java/sopt/org/umbba/common/sqs/dto/FCMPushRequestDto.java
  umbba-common/src/main/java/sopt/org/umbba/common/sqs/dto/PushMessage.java
  umbba-common/src/main/java/sopt/org/umbba/common/sqs/dto/SlackDto.java
  umbba-notification/src/main/java/sopt/org/umbba/notification/config/fcm/FCMConfig.java
  umbba-notification/src/main/java/sopt/org/umbba/notification/config/sqs/consumer/SqsConsumer.java
  umbba-notification/src/main/java/sopt/org/umbba/notification/service/fcm/FCMController.java
  umbba-notification/src/main/java/sopt/org/umbba/notification/service/fcm/FCMService.java
  umbba-notification/src/main/java/sopt/org/umbba/notification/service/slack/SlackApi.java
  umbba-notification/src/main/resources/application.yaml
Labels: 🔥 Pull Request, 예준🍒, ✨Feat

#94 [FEAT] SQS를 활용해 푸시서버에서 스케줄링과 Slack 알림을 발송하도록 구현
  umbba-api/src/main/java/sopt/org/umbba/api/config/SqsConfig.java
  umbba-api/src/main/java/sopt/org/umbba/api/controller/advice/ControllerExceptionAdvice.java
  umbba-api/src/main/java/sopt/org/umbba/api/service/notification/NotificationService.java
  umbba-api/src/main/java/sopt/org/umbba/api/service/parentchild/ParentchildService.java
  umbba-common/src/main/java/sopt/org/umbba/common/sqs/MessageType.java
  umbba-common/src/main/java/sopt/org/umbba/common/sqs/dto/FirebaseDto.java
  umbba-common/src/main/java/sopt/org/umbba/common/sqs/dto/ScheduleDto.java
  umbba-notification/src/main/java/sopt/org/umbba/notification/config/FCMConfig.java
  umbba-notification/src/main/java/sopt/org/umbba/notification/config/ScheduleConfig.java
  umbba-notification/src/main/java/sopt/org/umbba/notification/config/SqsConfig.java
  umbba-notification/src/main/java/sopt/org/umbba/notification/config/sqs/consumer/SqsConsumer.java
  umbba-notification/src/main/java/sopt/org/umbba/notification/service/fcm/FCMService.java
  umbba-notification/src/main/java/sopt/org/umbba/notification/service/scheduler/FCMScheduler.java
Labels: 🔥 Pull Request, 예준🍒, 동섭🍑, ✨Feat, 🔧Modify

#97 [FIX] 커넥션 누수를 해결하기 위해 em.close() 코드 추가
  umbba-api/src/main/java/sopt/org/umbba/api/config/sqs/producer/SqsProducer.java
  umbba-domain/src/main/java/sopt/org/umbba/domain/domain/parentchild/dao/ParentchildDao.java
  umbba-domain/src/main/java/sopt/org/umbba/domain/domain/qna/dao/QnADao.java
Labels: 🔥 Pull Request, 🚨Hotfix, 동섭🍑, ☁️Database

#98 [FIX] Warning 해결을 위한 수정사항 반영
  .github/workflows/api-CD.yml
  .github/workflows/notification-CD.yml
  umbba-notification/src/main/java/sopt/org/umbba/notification/service/fcm/FCMService.java
Labels: 동섭🍑, 🐞 BugFix, 🚀Deploy

#99 [HOTFIX] API가 중복 호출되어 QNA 리스트가 7개를 넘어가는 오류 해결
  umbba-common/src/main/java/sopt/org/umbba/common/exception/ErrorType.java
  umbba-domain/src/main/java/sopt/org/umbba/domain/domain/parentchild/Parentchild.java
Labels: 🔥 Pull Request, 🚨Hotfix, 동섭🍑

#101 [FEAT] 모든 질답 완료 시 응답값 구분
  umbba-api/src/main/java/sopt/org/umbba/api/service/qna/QnAService.java
Labels: 🔥 Pull Request, 예준🍒, 🪄API, 🔧Modify

#103 [FIX] 7일차 이후는 넘어가지 않도록 조건 추가
  umbba-notification/src/main/java/sopt/org/umbba/notification/service/fcm/FCMService.java
Labels: 🔥 Pull Request, 🚨Hotfix, 예준🍒, 🔧Modify
